/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/APDevTeam/Movecraft")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://maven.playpro.com")
    }
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.countercraft.movecraft)
    compileOnly(libs.net.coreprotect.coreprotect)
}

group = "net.countercraft.movecraft.coreprotect"
version = "1.0.0_beta-1"
description = "Movecraft-CoreProtect"
java.sourceCompatibility = JavaVersion.VERSION_13

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
