name: Movecraft-CoreProtect
version: '${project.version}'
main: net.countercraft.movecraft.coreprotect.movecraftcoreprotect.MovecraftCoreProtect
api-version: 1.14
depend: [ Movecraft, CoreProtect ]
authors: [ TylerS1066 ]
description: Movecraft Integration with CoreProtect
website: https://github.com/TylerS1066/Movecraft-CoreProtect
