name: Movecraft-CoreProtect
version: ${projectVersion}
main: net.countercraft.movecraft.coreprotect.MovecraftCoreProtect
api-version: 1.18
depend: [ Movecraft, CoreProtect ]
authors: [ TylerS1066 ]
description: Movecraft Integration with CoreProtect
website: https://github.com/APDevTeam/Movecraft-CoreProtect
