name: Gradle CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [created, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Movecraft-CoreProtect
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Build with Gradle
      run: ./gradlew clean build --parallel

    - name: Publish to GitHub Packages
      run: ./gradlew publish --parallel
      if: ${{ github.event_name == 'release' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage jar
      run: mkdir staging && cp build/libs/Movecraft-CoreProtect.jar staging && mv staging/Movecraft-CoreProtect.jar staging/Movecraft-CoreProtect_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Movecraft-CoreProtect_Dev-Build
        path: staging/Movecraft-CoreProtect_*.jar
