name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  # Build Movecraft-CoreProtect
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Movecraft-CoreProtect
        uses: actions/checkout@v2
        with:
          path: Movecraft-CoreProtect
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      
      # Build Movecraft-CoreProtect
      - name: Build Movecraft-CoreProtect
        run: mvn -B package -T 1C --file Movecraft-CoreProtect/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stage jar
        run: mkdir staging && cp Movecraft-CoreProtect/target/Movecraft-CoreProtect*.jar staging
      - name: Rename jar
        run: mv staging/Movecraft-CoreProtect*.jar staging/Movecraft-CoreProtect_$GITHUB_SHA.jar
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: Movecraft-CoreProtect_Dev-Build
          path: staging/Movecraft-CoreProtect_*.jar