name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  # Build Movecraft-CoreProtect
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Movecraft-CoreProtect
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew clean build publish --parallel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
